version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: image-server-app
    volumes:
      - images:/images
      - logs:/logs
      - ./static:/static
    ports:
      - "8000:8000"
    networks:
      - image-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: image-server-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - images:/images
      - ./static:/static
    ports:
      - "8080:80"
    depends_on:
      - app
    command: nginx -g "daemon off;"
    networks:
      - image-network
    restart: unless-stopped

volumes:
  images:
  logs:
  static:

networks:
  image-network:
    driver: bridge