version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: image-server-app
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - images:/images
      - logs:/logs
      - ./static:/static
    ports:
      - "8000:8000"
    networks:
      - image-network
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: image-server-db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - image-network
    ports:
      - "5432:5432"

  nginx:
    image: nginx:alpine
    container_name: image-server-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - images:/images
      - ./static:/static
    ports:
      - "8080:80"
    depends_on:
      - app
    command: nginx -g "daemon off;"
    networks:
      - image-network
    restart: unless-stopped

volumes:
  images:
  logs:
  static:
  pgdata:

networks:
  image-network:
    driver: bridge
